# Where things are
auto: true
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null


# Handling Reading
safe: false
include: [".htaccess"]
exclude: ["README.md", ".git", ".svn"]
keep_files: [ "manual/", "javascripts/", "stylesheets/", "images/"]
encoding : utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"


# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false


# Plugins
whitelist: []
gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap


# Conversion
markdown:    rdiscount
highlighter: pygments
pygments: true
lsi: true
excerpt_separator: "\n\n"


# Serving
detach:  false
port:    80
host:    http://github.tiankonguse.com
baseurl: "/" # does not include hostname
url: http://github.tiankonguse.com


# Backwards-compatibility
relative_permalinks: false

# Outputting

#year 文件名中的年份
#month 文件名中的月份
#day 文件名中的日期
#title 文件名中的文章标题
#categories 文章的分类，如果文章没有分类，会忽略

#i-month 文件名中的除去前缀0的月份
#i-day 文件名中的除去前缀0的日期

permalink: /blog/:year/:month/:day/:title/
paginate_path: page:num
paginate: 10
prelinkpath : ""
production_url : http://github.tiankonguse.com
timezone:      null
quiet:    false
defaults: []

# site info
author : "tiankonguse"
title: tiankonguse blog
description : 这是 tiankonguse 基于 Jekyll 和 github 创建的博客，是 tiankonguse 在学习上，工作上，生活上的记录。
feed: /atom.xml
author_info: <a href="http://github.tiankonguse.com">tiankonguse</a>
tagline: Site Tagline
description: 这是 PIZn 的又一个博客，它是基于 Jekyll 


sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
  
#评论信息
disqus:
  config: true
  id: piznblog