auto: true

# encoding default is utf-8

encoding : utf-8

# base url
# if you use your own domain, you should alter to your own domain.
# such as baseurl : http://tiankonguse.com

#baseurl : http://tiankonguse.github.io

author : "tiankonguse"

title: tiankonguse.github.io

url: http://tiankonguse.github.io

feed: /atom.xml

author_info: <a href="http://tiankonguse.github.io/">tiankonguse</a>



# post url 
#year 文件名中的年份
#month 文件名中的月份
#day 文件名中的日期
#title 文件名中的文章标题
#categories 文章的分类，如果文章没有分类，会忽略
#i-month 文件名中的除去前缀0的月份
#i-day 文件名中的除去前缀0的日期

permalink : /blog/:title

prelinkpath : "/blog/"

# markdown language

markdown : rdiscount
pygments: true
paginate: 8
permalink: /:title




